### ISSUE TITLE
What is sqdiff or it is a missing dependency ?

### ISSUE THREAD

**Issue by linuxenko** [Swatinem/virtualdom#3]
Just read the source of the `diff.js` to learn how you did implement it, i think, you miss [something](https://github.com/Swatinem/virtualdom/blob/master/lib/diff.js#L5) inside of the `dependencies` for the `package.json`.

**Comment by Swatinem** [comment]
This library was made ages ago using the `component` packager that used its own `component.json`: https://github.com/Swatinem/virtualdom/blob/master/component.json#L18
It is essentially just another git repo: https://github.com/Swatinem/diff
